### ISSUE TITLE
Food API

### ISSUE THREAD

**Issue by CotyW** [tlg-24-05-visa-sde-1/24-07-JavaScriptProject-Team3#1]
- [x] Get the fetch to work
- [x] get the image to display
- [x] get a list to display
- [x] get the list and images to interact
- [x] consider a carousel
- [ ] add CSS

**Comment by CotyW** [comment]
This is the first card for Food List.

**Comment by bhar1gitr** [comment]
I g i can work on this if you provide em all the details
