### ISSUE TITLE
Transportation API

### ISSUE THREAD

**Issue by CotyW** [tlg-24-05-visa-sde-1/24-07-JavaScriptProject-Team3#3]
- [x] openai documentation
- [x] quick demo
- [x] tailor gpt to travel w two destinations
- [x] only frontend needed
- [x] integrate into main app
- [ ] figure out a way to hide API keys on the deployment process

**Comment by clayanNEU** [comment]
looking at safe api key storage on github pages

**Comment by bhar1gitr** [comment]
To hide API keys you guys can use .env
