### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by CotyW** [tlg-24-05-visa-sde-1/24-07-JavaScriptProject-Team3#8]
- [x] containers labeled
- [x] text classes defined
- [x] div setup and spaced out correctly
- [x] header styled
- [x] footer styled
- [ ]

**Comment by bhar1gitr** [comment]
I solved the issue

**Comment by bhar1gitr** [comment]
![Screenshot 2024-07-31 212810](https://github.com/user-attachments/assets/56c5ffed-4d0c-4d15-a8f5-8b2b174d4702)

**Comment by clayanNEU** [comment]
added main container, and left and right columns
